name: Manual Trigger Workflow

# Configure Manual Trigger
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: simple echo
        run: echo "This is a manual trigger workflow. You can run it manually from the Actions tab."
